// Inkstroke (Calligraphic Verdict) as a Dopamine effect on the Swift backbone —
// mirror of the web `effect-inkstroke/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + the bespoke tempo (InkstrokeTempo.swift) + a tiny
// config naming its scalar params and packing them into the uniform struct}.
// Everything else — the `.dope` mapping, the OKLCH palette, the registry, the
// two-pass loop, the standard uniforms, the shadow geometry — is shared
// DopamineCore. The numeric/palette bag comes verbatim from the bundled `.dope`
// (the SAME bytes as the web). Unlike Solarbloom there is no whimsy-picked
// content glyph: the verdict is a fully analytic, data-driven stroke, so the
// factory carries no `pickBand` content (the gesture composes across the whole
// surface and ignores the anchor — see `usesOrigin = false`).

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// The single source of truth for the droplet cap: BOTH the MSL `#define
/// MAX_DROPS` and the integer-clamp const the `.dope` references
/// (`clampMax: "MAX_DROPS"`).
public let MAX_DROPS: Double = 64

/// Inkstroke: resolves a feeling → the flat `.dope` param bag. The drawable side
/// is Metal-only (below).
public final class Inkstroke: EffectFactory {
    public let name = "inkstroke"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("inkstroke.dope", bundle: .module)
    }

    /// Resolve via the shared loader. `MAX_DROPS` is the only const; `inkSeed`
    /// is the scatter key — both byte-identical to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: ["MAX_DROPS": MAX_DROPS], scatterKey: "inkSeed")
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `InkstrokeUniforms` + `packInkstrokeUniforms(...)` are now GENERATED by
// scripts/gen-uniforms.mjs into `InkstrokeUniforms.swift` (the SAME source that
// emits the MSL `struct InkstrokeUniforms`), so the Swift struct and the
// `.metal` struct cannot drift. The config below just supplies the standard
// half + the frame()/host-side extras and calls the generated packer.

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height (= half the stroke length), the per-frame (envelope
/// + stroke draw) hook, and the uniform packer that lays the resolved bag into
/// the struct.
public struct InkstrokeConfig: PassConfig {
    public typealias Uniforms = InkstrokeUniforms
    public var vertexFunction = "inkstroke_vertex"
    public var fragmentFunction = "inkstroke_fragment"
    // The gesture composes itself across the whole surface, so it ignores the
    // anchor (web: index.ts comment "no origin").
    public var usesOrigin = false
    public init() {}

    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        if case let .number(v)? = params["scale"] { return v * 0.5 }
        return 0.35
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        var overshoot = 1.0
        if case let .number(v)? = params["overshoot"] { overshoot = v }
        let amp = envelope(info.life, overshoot: overshoot)
        // The pen draws on its OWN ~360ms clock (bespoke tempo). The web `frame()`
        // feeds the "on twos"-snapped `animMs` to `strokeProgress` (the stroke can
        // share the cel jitter clock), so use `info.animMs` to match parity — NOT
        // the un-stepped elapsed time.
        return (amp, ["draw": strokeProgress(info.animMs)])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packInkstrokeUniforms`). The standard half + named scalars come from the
    /// generated code; here we just hand the frame extras straight through. The
    /// stroke is fully analytic (no baked-SDF / glyph texture), so there are no
    /// host-side texture-plumbing extras to top up (unlike Solarbloom).
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> InkstrokeUniforms {
        return packInkstrokeUniforms(standard: s, params: params, extras: extras)
    }
}
#endif
