// Aurora as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-aurora/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + a tiny config naming its scalar params, its (faint)
// shadow height, and the per-frame envelope + accumulated sideways SWEEP}.
// Everything else — the `.dope` mapping, the OKLCH palette, the registry, the
// two-pass loop, the standard uniforms, the shadow geometry — is shared
// DopamineCore. The numeric/palette bag comes verbatim from the bundled `.dope`
// (the SAME bytes as the web). Aurora is DIRECTIONAL/curtain, so unlike the
// radial Solarbloom it ignores the anchor (no origin) and has no functional
// glyph: there is no bespoke tempo, no oracle, no texture plumbing.

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// The single source of truth for the curtain count: BOTH the MSL
/// `#define CURTAINS` and the integer-clamp const the `.dope` references
/// (`MAX_CURTAINS`).
public let MAX_CURTAINS: Double = 7

/// Aurora: resolves a feeling → the flat `.dope` param bag. A calm, ambient
/// success effect — hanging curtains of polar light. The drawable side is
/// Metal-only (below).
public final class Aurora: EffectFactory {
    public let name = "aurora"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("aurora.dope", bundle: .module)
    }

    /// Resolve via the shared loader. `MAX_CURTAINS` is the only const;
    /// `auroraSeed` is the scatter key — both byte-identical to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: ["MAX_CURTAINS": MAX_CURTAINS], scatterKey: "auroraSeed")
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `AuroraUniforms` + `packAuroraUniforms(...)` are GENERATED by
// scripts/gen-uniforms.mjs into `AuroraUniforms.swift` (the SAME source that
// emits the MSL `struct AuroraUniforms`), so the Swift struct and the `.metal`
// struct cannot drift. The config below just supplies the standard half + the
// frame() extras and calls the generated packer.

/// Sideways sweep speed (fraction of width per second). Slow, ambient drift.
private let SWEEP_SPEED: Double = 0.02

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the (faint) shadow height (= band half-height, scaled down hard so a
/// real aurora barely occludes), the per-frame (envelope + accumulated sideways
/// sweep) hook, and the uniform packer that lays the resolved bag into the struct.
public struct AuroraConfig: PassConfig {
    public typealias Uniforms = AuroraUniforms
    public var vertexFunction = "aurora_vertex"
    public var fragmentFunction = "aurora_fragment"
    // Aurora is directional/curtain: it composes across the whole upper surface
    // and ignores the anchor, so it does NOT read origin.
    public var usesOrigin = false
    public init() {}

    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        // A real aurora barely occludes; the shader scales the cast shadow down
        // hard, so a modest height keeps the faint floating read without a heavy
        // silhouette.
        if case let .number(v)? = params["bandHeight"] { return v * 0.6 }
        return 0.6 * 0.6
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        var overshoot = 1.0
        if case let .number(v)? = params["overshoot"] { overshoot = v }
        let amp = envelope(info.life, overshoot: overshoot)
        // Accumulated sideways sweep (fraction of width). Slow ambient travel; the
        // sweep eases so the curtains drift in then settle rather than scroll forever.
        let sweep = SWEEP_SPEED * (info.animMs / 1000.0) * (1.0 - 0.5 * info.life)
        return (amp, ["sweep": sweep])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packAuroraUniforms`). The standard half + named scalars come from the
    /// generated code; here we only hand the frame() extras (the accumulated
    /// sweep) through, mirroring the web `frame()` hook.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> AuroraUniforms {
        return packAuroraUniforms(standard: s, params: params, extras: extras)
    }
}
#endif
