// @generated by scripts/gen-uniforms.mjs — do not edit
// Swift uniform struct + packer for aurora. Its memory layout MUST match
// `struct AuroraUniforms` in Shaders/AuroraUniforms.metal — gen-uniforms
// emits both from the same field list, so they cannot drift.
//
// The GLSL→MSL binding seam, datafied: the web's per-name `gl.uniform*` becomes
// this one packed struct, filled from the resolved `.dope` param bag by name.
#if canImport(Metal)
import simd
import DopamineCore

public struct AuroraUniforms {
    // standard (matches StandardUniforms order)
    public var resolution: SIMD2<Float> = SIMD2<Float>(0, 0)
    public var origin: SIMD2<Float> = SIMD2<Float>(0, 0)
    public var life: Float = 0
    public var timeS: Float = 0
    public var style: Float = 0
    public var amp: Float = 0
    public var c0: SIMD3<Float> = SIMD3<Float>(0, 0, 0)
    public var c1: SIMD3<Float> = SIMD3<Float>(0, 0, 0)
    public var c2: SIMD3<Float> = SIMD3<Float>(0, 0, 0)
    public var shadow: Float = 0
    public var shadowOffset: SIMD2<Float> = SIMD2<Float>(0, 0)
    public var shadowSoft: Float = 0
    public var shadowStrength: Float = 0
    // aurora render.params (auto-bound by name from the resolved bag)
    public var exposure: Float = 0
    public var coverage: Float = 0
    public var bandY: Float = 0
    public var bandHeight: Float = 0
    public var sway: Float = 0
    public var striation: Float = 0
    public var rays: Float = 0
    // scatter key (seed-keyed)
    public var auroraSeed: Float = 0
    // frame extras + plumbing (filled by frame()/host)
    public var sweep: Float = 0
    public init() {}
}

/// Pack the resolved bag → the struct. The standard half is copied from
/// `StandardUniforms`; each named scalar maps to its struct field (the web's
/// `u<Name>` auto-bind); `extras` carries the frame()/host values.
public func packAuroraUniforms(
    standard s: StandardUniforms,
    params: [String: DopeValue],
    extras: [String: Double]
) -> AuroraUniforms {
    var u = AuroraUniforms()
    // standard half
    u.resolution = s.resolution
    u.origin = s.origin
    u.life = s.life
    u.timeS = s.timeS
    u.style = s.style
    u.amp = s.amp
    u.c0 = s.c0
    u.c1 = s.c1
    u.c2 = s.c2
    u.shadow = s.shadow
    u.shadowOffset = s.shadowOffset
    u.shadowSoft = s.shadowSoft
    u.shadowStrength = s.shadowStrength
    // resolved scalar params (by name)
    func f(_ k: String) -> Float { if case let .number(v)? = params[k] { return Float(v) }; return 0 }
    u.exposure = f("exposure")
    u.coverage = f("coverage")
    u.bandY = f("bandY")
    u.bandHeight = f("bandHeight")
    u.sway = f("sway")
    u.striation = f("striation")
    u.rays = f("rays")
    u.auroraSeed = f("auroraSeed")
    // frame extras + plumbing
    u.sweep = Float(extras["sweep"] ?? 0)
    return u
}
#endif
