// @generated by scripts/gen-uniforms.mjs — do not edit
// MSL uniform struct for the confetti fragment shader. `#include` this from
// the `.metal` and read `constant ConfettiUniforms &u [[buffer(0)]]`. Field
// ORDER/types match the Swift `ConfettiUniforms` packer (gen-uniforms emits both).
#ifndef CONFETTI_UNIFORMS_H
#define CONFETTI_UNIFORMS_H
#include <metal_stdlib>
using namespace metal;

struct ConfettiUniforms {
    // --- standard (StandardUniforms, in declared order) ---
    float2 resolution;
    float2 origin;
    float  life;
    float  timeS;
    float  style;
    float  amp;
    float3 c0;
    float3 c1;
    float3 c2;
    float  shadow;
    float2 shadowOffset;
    float  shadowSoft;
    float  shadowStrength;
    // --- confetti render.params (auto-bound by name) ---
    float  exposure;
    float  pieceCount;
    float  spread;
    float  launchSpeed;
    float  gravity;
    float  flutter;
    float  pieceSize;
    float  spin;
    // --- scatter key (seed-keyed; read by name) ---
    float  pieceSeed;
};
#endif
