// @generated by scripts/gen-uniforms.mjs — do not edit
// MSL uniform struct for the fail fragment shader. `#include` this from
// the `.metal` and read `constant FailUniforms &u [[buffer(0)]]`. Field
// ORDER/types match the Swift `FailUniforms` packer (gen-uniforms emits both).
#ifndef FAIL_UNIFORMS_H
#define FAIL_UNIFORMS_H
#include <metal_stdlib>
using namespace metal;

struct FailUniforms {
    // --- standard (StandardUniforms, in declared order) ---
    float2 resolution;
    float2 origin;
    float  life;
    float  timeS;
    float  style;
    float  amp;
    float3 c0;
    float3 c1;
    float3 c2;
    float  shadow;
    float2 shadowOffset;
    float  shadowSoft;
    float  shadowStrength;
    // --- fail render.params (auto-bound by name) ---
    float  exposure;
    float  severity;
    // --- frame extras + plumbing (filled by frame()/host) ---
    float  stamp;   // stampProgress(animMs)
    float  shake;   // signed recoil shake (-1..1)
    float  sdfOn;   // 1 = drive the cross from the baked SDF
    float  sdfRangePx;   // device px mapping to the SDF 0..1 range
    float  sdfStrokePx;   // half stroke width (device px)
    float  boxPx;   // half-size (device px) of the ✗ box
};
#endif
