// Heartburst as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-heartburst/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + the bespoke tempo (HeartburstTempo.swift) + a tiny
// config naming its scalar params and packing them into the uniform struct}.
// Everything else — the `.dope` mapping, the warm OKLCH palette, the registry,
// the two-pass loop, the standard uniforms, the shadow geometry — is shared
// DopamineCore. The numeric/palette bag comes verbatim from the bundled `.dope`
// (the SAME bytes as the web).
//
// HYBRID (Canvas2D-panel) effect: the web draws the hero heart + the flurry of
// little burst hearts as vector heart curves into ONE offscreen Canvas2D panel
// each frame (heartburst-renderer.ts) and hands it to the shader as a texture.
// That `draw()` is the genuinely code-shaped JS that stays on the host side and
// does NOT port to MSL; this package contributes the shader (which lights that
// panel) + the bespoke beat/burst tempo, exactly the web's per-effect surface.

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// Heartburst: resolves a feeling → the flat `.dope` param bag. The drawable side
/// is Metal-only (below).
public final class Heartburst: EffectFactory {
    public let name = "heartburst"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("heartburst.dope", bundle: .module)
    }

    /// Resolve via the shared loader. Heartburst declares NO consts (web
    /// `consts: {}`); `heartburstSeed` is the scatter key — both byte-identical
    /// to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: [:], scatterKey: "heartburstSeed")
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `HeartburstUniforms` + `packHeartburstUniforms(...)` are now GENERATED by
// scripts/gen-uniforms.mjs into `HeartburstUniforms.swift` (the SAME source that
// emits the MSL `struct HeartburstUniforms`), so the Swift struct and the
// `.metal` struct cannot drift. The config below just supplies the standard
// half + the frame()/host-side extras and calls the generated packer.

/// The warm beat/burst FLASH amount over normalized life. Spikes hard on each
/// lub-dub thump (tracking the beat amplitude) and again at the burst release,
/// then decays. Pure function of life. Port of `index.ts` `heartFlash`.
private func heartFlash(_ life: Double, beatStrength: Double, doubleBeat: Double) -> Double {
    let beat = max(0, heartbeatScale(life, strength: beatStrength, doubleBeat: doubleBeat) - 1) // 0 at rest
    let b = burstProgress(life)
    let burstSpike = b > 0 ? exp(-pow((b - 0.06) / 0.12, 2)) : 0
    return min(1.2, beat * 1.6 + burstSpike * 0.8)
}

/// Overall panel presence over normalized life: a quick snap-in, a proud hold
/// through the beats + burst, then a clean fade at the tail so the panel clears.
/// Port of `index.ts` `heartPresence`.
private func heartPresence(_ life: Double) -> Double {
    let t = life < 0 ? 0 : (life > 1 ? 1 : life)
    if t < 0.04 { return t / 0.04 }
    if t < 0.8 { return 1 }
    let fade = 1 - (t - 0.8) / 0.2
    return pow(max(0, fade), 1.4)
}

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height (= heart scale × 1.1), the per-frame (presence + beat
/// + burst + flash) hook, and the uniform packer that lays the resolved bag into
/// the struct.
public struct HeartburstConfig: PassConfig {
    public typealias Uniforms = HeartburstUniforms
    public var vertexFunction = "heartburst_vertex"
    public var fragmentFunction = "heartburst_fragment"
    public var usesOrigin = true
    public init() {}

    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        if case let .number(v)? = params["heartScale"] { return v * 1.1 }
        return 0.3
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        // beatStrength / doubleBeat are DRAW-ONLY params (web bindings: null) but
        // the bespoke tempo reads them from the resolved bag here — exactly as the
        // web `frame()` reads `params.beatStrength` / `params.doubleBeat`.
        var beatStrength = 1.0
        if case let .number(v)? = params["beatStrength"] { beatStrength = v }
        var doubleBeat = 1.0
        if case let .number(v)? = params["doubleBeat"] { doubleBeat = v }

        let beat = max(0, heartbeatScale(info.life, strength: beatStrength, doubleBeat: doubleBeat) - 1)
        let amp = heartburstEnvelope(info.life, strength: beatStrength, doubleBeat: doubleBeat)
        return (amp, [
            "presence": heartPresence(info.life),
            "beat": min(1, beat * 2.2),
            "burst": burstProgress(info.life),
            "flash": heartFlash(info.life, beatStrength: beatStrength, doubleBeat: doubleBeat),
        ])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packHeartburstUniforms`). The standard half + named scalars come from the
    /// generated code; here we only top up the host-side extra (`dotSize`, the
    /// dpr-scaled halftone cell) that the web fills in `passUniforms`, then hand
    /// the full extras map to the generated packer.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> HeartburstUniforms {
        // dotSize is a resolved param in device px (pre-dpr); the web `passUniforms`
        // hook multiplies it by dpr on the host. We fill the un-scaled fallback so
        // the halftone blush still resolves when no host dpr override is supplied.
        var ex = extras
        if ex["dotSize"] == nil, case let .number(v)? = params["dotSize"] {
            ex["dotSize"] = v
        }
        return packHeartburstUniforms(standard: s, params: params, extras: ex)
    }
}
#endif
