// Lightning as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-lightning/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + the bespoke tempo (LightningTempo.swift) + a tiny
// config naming its scalar params and packing them into the uniform struct}.
// Everything else — the `.dope` mapping, the OKLCH palette, the registry, the
// two-pass loop, the standard uniforms, the shadow geometry — is shared
// DopamineCore. The numeric/palette bag comes verbatim from the bundled `.dope`
// (the SAME bytes as the web). Lightning has no whimsy-picked glyph; its only
// composed-on-top values are the strike/flash timing the frame() hook supplies.

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// The single source of truth for the secondary-fork cap: BOTH the MSL
/// `#define MAX_FORKS` and the integer-clamp const the `.dope` references
/// (`clampMax: "MAX_FORKS"`).
public let MAX_FORKS: Double = 7

/// Lightning: resolves a feeling → the flat `.dope` param bag. The drawable
/// side is Metal-only (below).
public final class Lightning: EffectFactory {
    public let name = "lightning"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("lightning.dope", bundle: .module)
    }

    /// Resolve via the shared loader. `MAX_FORKS` is the only const; `boltSeed`
    /// is the scatter key — both byte-identical to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: ["MAX_FORKS": MAX_FORKS], scatterKey: "boltSeed")
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `LightningUniforms` + `packLightningUniforms(...)` are now GENERATED by
// scripts/gen-uniforms.mjs into `LightningUniforms.swift` (the SAME source that
// emits the MSL `struct LightningUniforms`), so the Swift struct and the
// `.metal` struct cannot drift. The config below just supplies the standard
// half + the frame()/host-side extras and calls the generated packer.

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height (= a bright, fairly tall occluder so the cast bolt
/// reads as a sharp silhouette), the per-frame (strike + flash + envelope) hook,
/// and the uniform packer that lays the resolved bag into the struct.
public struct LightningConfig: PassConfig {
    public typealias Uniforms = LightningUniforms
    public var vertexFunction = "lightning_vertex"
    public var fragmentFunction = "lightning_fragment"
    public var usesOrigin = true
    public init() {}

    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        // A bright, fairly tall occluder so the cast shadow reads as a sharp
        // silhouette (web: `thickness * 14 + 0.4`).
        if case let .number(v)? = params["thickness"] { return v * 14 + 0.4 }
        return 0.4
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        var overshoot = 1.0
        if case let .number(v)? = params["overshoot"] { overshoot = v }
        var flicker = 1.0
        if case let .number(v)? = params["flicker"] { flicker = v }
        let amp = envelope(info.life, overshoot: overshoot)
        // The bolt cracks in on its OWN ~130ms clock (bespoke tempo) using the
        // REAL elapsed time, and the flash/strobe is keyed off normalized life
        // (peaks on contact + the flicker beats) — both composed on top of the
        // resolved bag, mirroring the web `frame()` hook.
        return (amp, [
            "strike": strikeProgress(info.elapsedMs),
            "flash": flashStrobe(info.life, flicker: flicker),
        ])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packLightningUniforms`). The standard half + named scalars come from the
    /// generated code; here we only hand the frame() extras (strike/flash) to it.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> LightningUniforms {
        packLightningUniforms(standard: s, params: params, extras: extras)
    }
}
#endif
