// Comic Impact as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-comic/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + the bespoke tempo (ComicTempo.swift) + a tiny config
// naming its scalar params and packing them into the uniform struct}. Everything
// else — the `.dope` mapping, the OKLCH palette, the registry, the two-pass loop,
// the standard uniforms, the shadow geometry — is shared DopamineCore. The
// numeric/palette bag comes verbatim from the bundled `.dope` (the SAME bytes as
// the web); the seed-picked SLAMMED word is composed on top with the shared
// `pickFromList` (no effect on the numeric/palette parity).
//
// HYBRID NOTE: in the web, Comic also draws a Canvas2D PANEL (word/burst/ink)
// each frame and the typography is mood-resolved; that panel + font pipeline is
// host-side (the web `createPanelInstance` runner). The pure-shader Swift
// backbone has no panel runner, so the panel texture is host-uploaded (mirroring
// how Solarbloom's check-glyph/SDF textures are host-uploaded), and the only
// non-numeric thing composed here is the per-fire word token — the comic analog
// of Solarbloom's `pickCheckGlyph`.

import Foundation
import DopamineCore

/// Comic Impact: resolves a feeling → the flat `.dope` param bag (+ the picked
/// SLAMMED word). The drawable side is Metal-only (below).
public final class Comic: EffectFactory {
    public let name = "comic"
    public let doc: DopeDoc
    private let pool: [String]

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("comic.dope", bundle: .module)
        // The per-fire SLAMMED token POOL (words + the checkmark sentinel, equal
        // odds) lives in the .dope content section.
        var words: [String] = []
        if let arr = doc.raw["content"]?["pool"]?.asArray {
            for w in arr {
                if let s = w.asString { words.append(s) }
            }
        }
        self.pool = words.isEmpty ? ["DONE!"] : words
    }

    /// Resolve via the shared loader. There are no consts; `comicSeed` is the
    /// scatter key — both byte-identical to the web call
    /// (`resolveDopeParams(DOPE, feeling, {}, "comicSeed")`).
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: [:], scatterKey: "comicSeed")
    }

    /// The per-fire SLAMMED word, picked from the pool by seed (composed on top
    /// of the numeric bag, exactly like the web `pickFromList(pool, seed)`).
    public func pickWord(seed: UInt32) -> String {
        pickFromList(pool, seed: seed)
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `ComicUniforms` + `packComicUniforms(...)` are GENERATED by
// scripts/gen-uniforms.mjs into `ComicUniforms.swift` (the SAME source that emits
// the MSL `struct ComicUniforms`), so the Swift struct and the `.metal` struct
// cannot drift. The config below just supplies the standard half + the
// frame()/host-side extras and calls the generated packer.

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height, the per-frame (presence + flash) hook, and the
/// uniform packer that lays the resolved bag into the struct.
public struct ComicConfig: PassConfig {
    public typealias Uniforms = ComicUniforms
    public var vertexFunction = "comic_vertex"
    public var fragmentFunction = "comic_fragment"
    public var usesOrigin = true
    public init() {}

    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        // The web `PanelConfig.shadowHeightFrac` is a constant 0.5 (the panel's
        // implied occluder height); no `.dope` param drives it.
        0.5
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        // The slam SCALE + the panel DRAW are host-side (the Canvas2D panel
        // runner); here we mirror the web `frame()` hook: presence feeds both the
        // shadow geometry amp AND uPresence, and the impact flash is the fast
        // spike that throws cast light (clamped as before).
        let presence = impactPresence(info.life)
        let flash =
            exp(-info.elapsedMs / (IMPACT_MS * 0.55)) +
            0.25 * exp(-abs(info.elapsedMs - IMPACT_HOLD_MS * 0.2) / (IMPACT_MS * 0.8))
        return (presence, ["presence": presence, "flash": min(flash, 1.2)])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packComicUniforms`). The standard half + named scalars come from the
    /// generated code; here we only top up the host-side extras (the dpr-scaled
    /// Ben-Day cell size + the style-fattened ink boost) that the web fills in its
    /// `passUniforms` hook, then hand the full extras map to the generated packer.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> ComicUniforms {
        // dotSize is authored at 1x dpr; the host multiplies by the live dpr.
        // inkBoost fattens the ink toward the pop end. Both mirror the web
        // `passUniforms`; the host may override dotSize with the true dpr, so we
        // fill the dpr=1 fallback here so the shader still draws.
        var ex = extras
        if ex["dotSize"] == nil {
            if case let .number(v)? = params["dotSize"] { ex["dotSize"] = v } else { ex["dotSize"] = 8 }
        }
        if ex["inkBoost"] == nil { ex["inkBoost"] = 1.0 + Double(s.style) * 0.4 }
        return packComicUniforms(standard: s, params: params, extras: ex)
    }
}
#endif
