// @generated by scripts/gen-uniforms.mjs — do not edit
// MSL uniform struct for the ripple fragment shader. `#include` this from
// the `.metal` and read `constant RippleUniforms &u [[buffer(0)]]`. Field
// ORDER/types match the Swift `RippleUniforms` packer (gen-uniforms emits both).
#ifndef RIPPLE_UNIFORMS_H
#define RIPPLE_UNIFORMS_H
#include <metal_stdlib>
using namespace metal;

struct RippleUniforms {
    // --- standard (StandardUniforms, in declared order) ---
    float2 resolution;
    float2 origin;
    float  life;
    float  timeS;
    float  style;
    float  amp;
    float3 c0;
    float3 c1;
    float3 c2;
    float  shadow;
    float2 shadowOffset;
    float  shadowSoft;
    float  shadowStrength;
    // --- ripple render.params (auto-bound by name) ---
    float  exposure;
    float  amplitude;
    float  rings;
    float  wavelength;
    float  speed;
    float  caustic;
    // --- scatter key (seed-keyed; read by name) ---
    float  rippleSeed;
};
#endif
