// Ripple as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-ripple/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + a tiny config naming its scalar params and packing them
// into the uniform struct}. Everything else — the `.dope` mapping, the OKLCH
// palette, the registry, the two-pass loop, the standard uniforms, the shadow
// geometry — is shared DopamineCore. The numeric/palette bag comes verbatim from
// the bundled `.dope` (the SAME bytes as the web). Ripple has NO bespoke tempo:
// its global brightness is the GENERIC held-breath `envelope` (see frame()), so
// unlike Solarbloom there is no RippleTempo file.

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// The single source of truth for the ring cap: BOTH the MSL `#define MAX_RINGS`
/// and the integer-clamp const the `.dope` references (`clampMax: "MAX_RINGS"`).
public let MAX_RINGS: Double = 7
/// The floor the `.dope` references (`clampMin: "MIN_RINGS"`).
public let MIN_RINGS: Double = 2

/// Ripple: resolves a feeling → the flat `.dope` param bag. The drawable side is
/// Metal-only (below).
public final class Ripple: EffectFactory {
    public let name = "ripple"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("ripple.dope", bundle: .module)
    }

    /// Resolve via the shared loader. `MAX_RINGS`/`MIN_RINGS` are the only consts;
    /// `rippleSeed` is the scatter key — both byte-identical to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: ["MAX_RINGS": MAX_RINGS, "MIN_RINGS": MIN_RINGS], scatterKey: "rippleSeed")
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `RippleUniforms` + `packRippleUniforms(...)` are now GENERATED by
// scripts/gen-uniforms.mjs into `RippleUniforms.swift` (the SAME source that
// emits the MSL `struct RippleUniforms`), so the Swift struct and the `.metal`
// struct cannot drift. The config below just supplies the standard half + the
// frame() envelope and calls the generated packer.

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height (= the wave field's outward reach), the per-frame
/// envelope hook, and the uniform packer that lays the resolved bag into the
/// struct.
public struct RippleConfig: PassConfig {
    public typealias Uniforms = RippleUniforms
    public var vertexFunction = "ripple_vertex"
    public var fragmentFunction = "ripple_fragment"
    public var usesOrigin = true
    public init() {}

    /// The wave field's outward reach (≈ rings * wavelength) sets the occluder
    /// "height" the troughs cast their faint shadow over.
    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        var wavelength = 0.0, rings = 0.0, amplitude = 0.0
        if case let .number(v)? = params["wavelength"] { wavelength = v }
        if case let .number(v)? = params["rings"] { rings = v }
        if case let .number(v)? = params["amplitude"] { amplitude = v }
        return min(wavelength * rings * 0.6 + amplitude * 0.3, 1)
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        var overshoot = 1.0
        if case let .number(v)? = params["overshoot"] { overshoot = v }
        let amp = envelope(info.life, overshoot: overshoot)
        // Ripple has no per-frame extras (no checkmark / texture plumbing); the
        // envelope amp gates global brightness + the shadow geometry.
        return (amp, [:])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packRippleUniforms`). The standard half + named scalars come from the
    /// generated code; Ripple has no host-side extras to top up, so the extras
    /// map passes straight through.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> RippleUniforms {
        return packRippleUniforms(standard: s, params: params, extras: extras)
    }
}
#endif
