// Fail / error as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-fail/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + the bespoke tempo (FailTempo.swift) + a tiny config
// naming its scalar params and packing them into the uniform struct}.
// Everything else — the `.dope` mapping, the OKLCH palette, the registry, the
// two-pass loop, the standard uniforms, the shadow geometry, the ✗ icon's
// geometry→SDF seam — is shared DopamineCore. The numeric/palette bag comes
// verbatim from the bundled `.dope` (the SAME bytes as the web). The fail feel
// is the emotional OPPOSITE of the success effects: a stamped ✗ over a recoiling
// error flare, then a fast desaturated collapse — no afterglow, no celebration.

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// Fail: resolves a feeling → the flat `.dope` param bag. The drawable side is
/// Metal-only (below).
public final class Fail: EffectFactory {
    public let name = "fail"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("fail.dope", bundle: .module)
    }

    /// Resolve via the shared loader. There are NO consts (web `consts: {}`);
    /// `failSeed` is the scatter key — both byte-identical to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: [:], scatterKey: "failSeed")
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `FailUniforms` + `packFailUniforms(...)` are GENERATED by
// scripts/gen-uniforms.mjs into `FailUniforms.swift` (the SAME source that emits
// the MSL `struct FailUniforms`), so the Swift struct and the `.metal` struct
// cannot drift. The config below just supplies the standard half + the
// frame()/host-side extras and calls the generated packer.

/// Half-size of the ✗ box as a fraction of min viewport dim.
private let CROSS_BOX_FRAC: Float = 0.15

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height (= flare reach), the per-frame (envelope + stamp +
/// shake) hook, and the uniform packer that lays the resolved bag into the struct.
public struct FailConfig: PassConfig {
    public typealias Uniforms = FailUniforms
    public var vertexFunction = "fail_vertex"
    public var fragmentFunction = "fail_fragment"
    public var usesOrigin = true
    public init() {}

    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        // Constant in the web (`shadowHeightFrac: 0.42`): the error casts a tight,
        // compact shadow — not a wide celebratory bloom.
        0.42
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        // The fail amplitude is a hard NEGATIVE jolt (failEnvelope): a near-instant
        // slam to full, a brief curt hold, then a fast collapse. The ✗ stamps in on
        // its OWN ~170ms clock; the recoil shake decays fast over ~300ms. Both use
        // the REAL elapsed time so the slam reads as punchy even when stylized.
        let amp = failEnvelope(info.life)
        var shakeAmount = 1.0
        if case let .number(v)? = params["shakeAmount"] { shakeAmount = v }
        return (amp, [
            "stamp": stampProgress(info.elapsedMs),
            "shake": shakeOffset(info.elapsedMs, amount: shakeAmount),
        ])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packFailUniforms`). The standard half + named scalars come from the
    /// generated code; here we only top up the host-side extras (the ✗ box +
    /// SDF stroke px) that depend on the live canvas, mirroring the web
    /// `passUniforms` hook, then hand the full extras map to the generated packer.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> FailUniforms {
        // boxPx / sdfStrokePx are needed even in the analytic (SDF-less) fallback.
        // The host may override, but we fill the analytic-fallback default so the
        // shader still draws when no SDF is bound. sdfOn stays 0 until the host
        // uploads the baked ✗ SDF texture and flips it on.
        var ex = extras
        let minDim = Float(min(s.resolution.x, s.resolution.y))
        let boxPx = CROSS_BOX_FRAC * minDim
        if ex["boxPx"] == nil { ex["boxPx"] = Double(boxPx) }
        if ex["sdfStrokePx"] == nil { ex["sdfStrokePx"] = Double(boxPx * 0.13) }
        return packFailUniforms(standard: s, params: params, extras: ex)
    }
}
#endif
