// @generated by scripts/gen-uniforms.mjs — do not edit
// MSL uniform struct for the heartburst fragment shader. `#include` this from
// the `.metal` and read `constant HeartburstUniforms &u [[buffer(0)]]`. Field
// ORDER/types match the Swift `HeartburstUniforms` packer (gen-uniforms emits both).
#ifndef HEARTBURST_UNIFORMS_H
#define HEARTBURST_UNIFORMS_H
#include <metal_stdlib>
using namespace metal;

struct HeartburstUniforms {
    // --- standard (StandardUniforms, in declared order) ---
    float2 resolution;
    float2 origin;
    float  life;
    float  timeS;
    float  style;
    float  amp;
    float3 c0;
    float3 c1;
    float3 c2;
    float  shadow;
    float2 shadowOffset;
    float  shadowSoft;
    float  shadowStrength;
    // --- heartburst render.params (auto-bound by name) ---
    float  exposure;
    float  glow;
    float  gloss;
    float  halftone;
    float  saturation;
    // --- scatter key (seed-keyed; read by name) ---
    float  heartburstSeed;
    // --- frame extras + plumbing (filled by frame()/host) ---
    float  presence;   // panel opacity / presence 0..1
    float  beat;   // 0..1 current beat amplitude (lub-dub thump)
    float  burst;   // 0..1 burst progress (little hearts flying out)
    float  flash;   // 0..1 warm beat/burst flash amount
    float  dotSize;   // halftone cell size in device px (dpr-scaled)
};
#endif
