// Confetti as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-confetti/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + the bespoke tempo (ConfettiTempo.swift) + a tiny
// config naming its scalar params and packing them into the uniform struct}.
// Everything else — the `.dope` mapping, the OKLCH palette, the registry, the
// two-pass loop, the standard uniforms, the shadow geometry — is shared
// DopamineCore. The numeric/palette bag comes verbatim from the bundled `.dope`
// (the SAME bytes as the web). Confetti has no glyph/SDF composition: it is
// purely a particle field, so unlike Solarbloom there is no whimsy-picked glyph.

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// The single source of truth for the piece cap: BOTH the MSL `#define MAX_PIECES`
/// and the integer-clamp const the `.dope` references (`clampMax: "MAX_PIECES"`).
public let MAX_PIECES: Double = 120

/// Confetti: resolves a feeling → the flat `.dope` param bag. The drawable side
/// is Metal-only (below).
public final class Confetti: EffectFactory {
    public let name = "confetti"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("confetti.dope", bundle: .module)
    }

    /// Resolve via the shared loader. `MAX_PIECES` is the only const; `pieceSeed`
    /// is the scatter key — both byte-identical to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: ["MAX_PIECES": MAX_PIECES], scatterKey: "pieceSeed")
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `ConfettiUniforms` + `packConfettiUniforms(...)` are now GENERATED by
// scripts/gen-uniforms.mjs into `ConfettiUniforms.swift` (the SAME source that
// emits the MSL `struct ConfettiUniforms`), so the Swift struct and the
// `.metal` struct cannot drift. The config below just supplies the standard
// half + the frame() amplitude and calls the generated packer.

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height (the launched + falling cloud spans a good chunk of
/// the viewport), the per-frame launch-then-fall amplitude envelope, and the
/// uniform packer that lays the resolved bag into the struct.
public struct ConfettiConfig: PassConfig {
    public typealias Uniforms = ConfettiUniforms
    public var vertexFunction = "confetti_vertex"
    public var fragmentFunction = "confetti_fragment"
    public var usesOrigin = true
    public init() {}

    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        // The launched + falling cloud spans a good chunk of the viewport; give
        // the shadow a moderate occluder "height". Matches the web SHADOW_HEIGHT_FRAC.
        0.5
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        // The launch-then-fall amplitude `confettiAmp` is Confetti's bespoke
        // timing — a sharp POP attack (overshoot at launch), a long luminous
        // sustain through the fall, then a soft fade as the last pieces settle.
        var overshoot = 1.0
        if case let .number(v)? = params["overshoot"] { overshoot = v }
        let amp = confettiAmp(info.life, overshoot: overshoot)
        return (amp, [:])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packConfettiUniforms`). The standard half + named scalars come from the
    /// generated code; confetti has no host-side extras (no glyph/SDF), so we
    /// pass the frame extras through untouched.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> ConfettiUniforms {
        packConfettiUniforms(standard: s, params: params, extras: extras)
    }
}
#endif
