// @generated by scripts/gen-uniforms.mjs — do not edit
// MSL uniform struct for the inkstroke fragment shader. `#include` this from
// the `.metal` and read `constant InkstrokeUniforms &u [[buffer(0)]]`. Field
// ORDER/types match the Swift `InkstrokeUniforms` packer (gen-uniforms emits both).
#ifndef INKSTROKE_UNIFORMS_H
#define INKSTROKE_UNIFORMS_H
#include <metal_stdlib>
using namespace metal;

struct InkstrokeUniforms {
    // --- standard (StandardUniforms, in declared order) ---
    float2 resolution;
    float2 origin;
    float  life;
    float  timeS;
    float  style;
    float  amp;
    float3 c0;
    float3 c1;
    float3 c2;
    float  shadow;
    float2 shadowOffset;
    float  shadowSoft;
    float  shadowStrength;
    // --- inkstroke render.params (auto-bound by name) ---
    float  exposure;
    float  scale;
    float  pressure;
    float  wetness;
    float  bristle;
    float  droplets;
    // --- scatter key (seed-keyed; read by name) ---
    float  inkSeed;
    // --- frame extras + plumbing (filled by frame()/host) ---
    float  draw;   // strokeProgress(animMs) — pen draw 0..1
};
#endif
