// @generated by scripts/gen-uniforms.mjs — do not edit
// MSL uniform struct for the comic fragment shader. `#include` this from
// the `.metal` and read `constant ComicUniforms &u [[buffer(0)]]`. Field
// ORDER/types match the Swift `ComicUniforms` packer (gen-uniforms emits both).
#ifndef COMIC_UNIFORMS_H
#define COMIC_UNIFORMS_H
#include <metal_stdlib>
using namespace metal;

struct ComicUniforms {
    // --- standard (StandardUniforms, in declared order) ---
    float2 resolution;
    float2 origin;
    float  life;
    float  timeS;
    float  style;
    float  amp;
    float3 c0;
    float3 c1;
    float3 c2;
    float  shadow;
    float2 shadowOffset;
    float  shadowSoft;
    float  shadowStrength;
    // --- comic render.params (auto-bound by name) ---
    float  exposure;
    float  actionLines;
    float  halftone;
    float  saturation;
    // --- scatter key (seed-keyed; read by name) ---
    float  comicSeed;
    // --- frame extras + plumbing (filled by frame()/host) ---
    float  presence;   // impactPresence(life)
    float  flash;   // 0..1 impact flash (fast spike, decays)
    float  dotSize;   // Ben-Day cell size (device px = dotSize*dpr)
    float  inkBoost;   // ink darkness/spread (1 + style*0.4)
};
#endif
